vich_uploader:
    db_driver: orm

    mappings:
        recipe:
            uri_prefix: /images/recipe
            upload_destination: '%kernel.project_dir%/public/images/recipe'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        user:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/images/user'
            namer: Vich\UploaderBundle\Naming\UniqidNamer